spring.application.name=LiveChatBufferService

server.port = 8062
server.servlet.context-path = /v1/transcripts/

# ===============================
# = REDIS
# ===============================
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.useSSL=false


